import type { Metadata } from "next"; // Next.js metadata type
import "./globals.css"; // Global CSS styles
import Navbar from "@/components/navbar"; // Navigation component
import { PT_Sans } from "next/font/google"; // Google font

const ptSans = PT_Sans({
  // Font configuration
  subsets: ["latin"],
  weight: ["400", "700"], // Font weights
  display: "swap", // Font display strategy
});

export const metadata: Metadata = {
  // App metadata
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  // Root layout component
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html // HTML root
      lang="en"
      className={`${ptSans.className} ${ptSans.className} h-full antialiased`} // Font and styles
    >
      <body className="min-h-full flex flex-col">
        <Navbar />
        {children}
      </body>
    </html>
  );
}
